# Generated by Django 6.0.2 on 2026-03-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Gênero')),
                ('cover_image', models.URLField(blank=True, verbose_name='URL da Capa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Lista')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_public', models.BooleanField(default=False, verbose_name='Lista Pública')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lista de Jogos',
                'verbose_name_plural': 'Listas de Jogos',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GameListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Jogo')),
                ('game_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gamelist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Item da Lista',
                'verbose_name_plural': 'Itens da Lista',
                'ordering': ['-added_at'],
                'unique_together': {('game_list', 'game')},
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('playing', 'Jogando'), ('completed', 'Concluído'), ('paused', 'Pausado'), ('dropped', 'Abandonado'), ('plan_to_play', 'Planejo Jogar')], default='plan_to_play', max_length=20, verbose_name='Status')),
                ('progress', models.IntegerField(default=0, help_text='Progresso em porcentagem (0-100)', verbose_name='Progresso')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada da Biblioteca',
                'verbose_name_plural': 'Entradas da Biblioteca',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nota (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
