# Generated by Django 6.0.3 on 2026-05-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useremailverification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
