# Generated by Django 6.0.3 on 2026-05-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização'),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_app_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Steam App ID'),
        ),
    ]
