# Generated by Django 6.0.3 on 2026-05-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_last_synced_at_game_steam_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tipo Steam'),
        ),
    ]
