# Generated by Django 6.0.3 on 2026-05-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game_steam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=32, unique=True, verbose_name='Steam ID')),
                ('persona_name', models.CharField(blank=True, max_length=200, verbose_name='Nome publico Steam')),
                ('profile_url', models.URLField(blank=True, verbose_name='URL do perfil Steam')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Avatar Steam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo login Steam')),
                ('last_library_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima sincronizacao da biblioteca')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steam_account_link', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conta Steam vinculada',
                'verbose_name_plural': 'Contas Steam vinculadas',
            },
        ),
    ]
