# Generated by Django 6.0.2 on 2026-05-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.CharField(blank=True, max_length=255, verbose_name='Desenvolvedor'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.CharField(blank=True, max_length=255, verbose_name='Distribuidora'),
        ),
    ]
