# Generated by Django 6.0.2 on 2026-05-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_developers_game_publishers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='achievement_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Conquistas'),
        ),
        migrations.AddField(
            model_name='game',
            name='system_requirements_min',
            field=models.TextField(blank=True, verbose_name='Requisitos Minimos'),
        ),
        migrations.AddField(
            model_name='game',
            name='system_requirements_rec',
            field=models.TextField(blank=True, verbose_name='Requisitos Recomendados'),
        ),
    ]
