# Generated by Django 6.0.2 on 2026-05-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_game_achievement_count_game_system_requirements_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='achievement_count',
        ),
    ]
